name: xlogger
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Go-oG/xlogger.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  jovial_misc: ^0.8.3
  pointycastle: ^3.4.0
  archive: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.goog.xlogger
        pluginClass: XloggerPlugin
      ios:
        pluginClass: XloggerPlugin